Repository GDSC-IIIT-Kalyani/Hacktober-Fest-2023, pull requests merged in 2023-10, with the labels that each got.

#4 Faq section added with complete responsiveness and footer with deskto…
  dist/assets/05@1x 1.svg
  dist/assets/FAQ.svg
  dist/assets/Line 28.svg
  dist/assets/Rectangle 25.svg
  dist/assets/Screenshot 2023-09-18 123007 4.svg
  dist/assets/Screenshot 2023-09-21 004136 1.svg
  dist/assets/hf10_icon_fcd_rgb 2.svg
  dist/assets/image 1.svg
  dist/index.html
  dist/index.js
  dist/output.css
  src/input.css
  tailwind.config.js
Labels: hacktoberfest-accepted

#13 responsive footer
  dist/index.html
  dist/output.css
Labels: enhancement, hacktoberfest-accepted

#17 changes on 11 oct 2:18
  __pycache__/app.cpython-311.pyc
  app.py
  templates/index.html
Labels: hacktoberfest-accepted, level-2

#18 fixed minor issues.
  dist/index.html
  dist/output.css
  tailwind.config.js
Labels: enhancement, hacktoberfest-accepted, level-2

#25 updated team section
  __pycache__/app.cpython-311.pyc
  static/assets/anushka_avatar1.png
  static/assets/aryan_avatar.jpeg
  static/assets/icons8-github.svg
  static/assets/linkedin.png
  static/assets/linkedin.svg
  static/assets/mohit_avatar1.jpg
  static/assets/raunak_avatar.png
  static/assets/shoeb_avatar.jpeg
  static/assets/subhadeep_avatar.jpg
  static/assets/twitter.svg
  static/css/output.css
  templates/index.html
Labels: hacktoberfest-accepted, level-2

#26 Addition to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, hacktoberfest-accepted, level-1

#28 patches
  .vscode/settings.json
  templates/index.html
Labels: hacktoberfest-accepted, level-2

#30 Merge 'main' into 'dev/minor-fixes'
  .gitignore
  __pycache__/app.cpython-311.pyc
  static/css/output.css
  templates/index.html
Labels: hacktoberfest-accepted, level-3

#32 faq updated
  __pycache__/app.cpython-311.pyc
  static/css/output.css
  static/js/index.js
  templates/index.html
Labels: hacktoberfest-accepted, level-2
